module.exports = [
	{ name: 'ĐƯỜNG ĐỜI', key: 0 },
	{ name: 'SỨ MỆNH', key: 1 },
	{ name: 'TRƯỞNG THÀNH', key: 2 },
	{ name: 'CẦU NỐI ĐƯỜNG ĐỜI/SỨ MỆNH', key: 3 },
	{ name: 'SỐ NGÀY SINH', key: 4 },
	{ name: 'KHÁT TÂM', key: 5 },
	{ name: 'NHÂN CÁCH', key: 6 },
	{ name: 'CẦU NỐI KHÁT TÂM/NHÂN CÁCH', key: 7 },
	{ name: 'ĐAM MÊ TIỀM ẨN', key: 8 },
	{ name: 'BÀI HỌC CUỘC SỐNG', key: 9 },
	{ name: 'TIỀM THỨC ẨN', key: 10 },
	{ name: 'SỐ SUY NGHĨ HỢP LÝ', key: 11 },
	{ name: 'SỐ CÂN BẰNG', key: 12 },
	{ name: 'NỀN TẢNG', key: 13 },
	{ name: 'THỂ CHẤT', key: 14 },
	{ name: 'TINH THẦN', key: 15 },
	{ name: 'CẢM XÚC', key: 16 },
	{ name: 'TRỰC GIÁC', key: 17 },
	{ name: 'CHU KỲ 1', key: 18 },
	{ name: 'CHU KỲ 2', key: 19 },
	{ name: 'CHU KỲ 3', key: 20 },
	{ name: 'ĐỈNH CAO 1', key: 21 },
	{ name: 'ĐỈNH CAO 2', key: 22 },
	{ name: 'ĐỈNH CAO 3', key: 23 },
	{ name: 'ĐỈNH CAO 4', key: 24 },
	{ name: 'THÁCH THỨC 1', key: 25 },
	{ name: 'THÁCH THỨC 2', key: 26 },
	{ name: 'THÁCH THỨC 3', key: 27 },
	{ name: 'THÁCH THỨC 4', key: 28 },
	{ name: 'NĂM CÁ NHÂN 2021', key: 29 },
	{ name: 'NĂM CÁ NHÂN 2022', key: 30 },
	{ name: 'NĂM CÁ NHÂN 2023', key: 31 },
];
